# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: algebra.f32.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'algebra.f32.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61lgebra.f32.proto\x12\x0b\x61lgebra.f32\"\'\n\x04Vec3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"2\n\x04Quat\x12\t\n\x01w\x18\x01 \x01(\x02\x12\t\n\x01i\x18\x02 \x01(\x02\x12\t\n\x01j\x18\x03 \x01(\x02\x12\t\n\x01k\x18\x04 \x01(\x02\"i\n\x04Mat3\x12\x1f\n\x04\x63ol1\x18\x01 \x01(\x0b\x32\x11.algebra.f32.Vec3\x12\x1f\n\x04\x63ol2\x18\x02 \x01(\x0b\x32\x11.algebra.f32.Vec3\x12\x1f\n\x04\x63ol3\x18\x03 \x01(\x0b\x32\x11.algebra.f32.Vec3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'algebra.f32_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VEC3']._serialized_start=34
  _globals['_VEC3']._serialized_end=73
  _globals['_QUAT']._serialized_start=75
  _globals['_QUAT']._serialized_end=125
  _globals['_MAT3']._serialized_start=127
  _globals['_MAT3']._serialized_end=232
# @@protoc_insertion_point(module_scope)
