data = {
    "1x (NoScale)": "1x (无缩放)",
    "Connected": "已连接",
    "Pure Input": "纯输入",
    "Lock Transition": "锁定过渡",
    "Translation Scale": "变换缩放",
    "Recording": "录制",
    "No armature available": "无活动骨骼",
    "Map Version": "映射版本",
    "Auto Animate Map": "自动动画映射",
    "Auto Map Bone": "自动映射骨骼",
    "Apply": "应用",
    "Update Available!!!": "更新可用!!!",
    "Found Scene Object: %s": "找到场景物体: %s",
    "Read Meocap Recording file: %s with %i frames": "读取 Meocap 录制文件: %s 有 %i 帧",
    "Failed to Read file: %s": "读取文件失败: %s",
    "Open Meocap Retarget file: %s": "打开 Meocap 录制文件: %s",
    "Failed to Open file: %s": "打开文件失败: %s",
    "Start": "开始",
    "Disconnect": "断开",
    "Connect": "连接",
    "End": "结束",
    "Export": "导出",
    "Save Meocap Retarget file: %s": "保存 Meocap 录制文件: %s",
    "Create Retarget Config": "创建录制配置",
    "Executing Init Retarget Config": "正在执行初始化重定向配置",
    "Armature Bone Object": "骨骼骨架物体",
    "Meocap Performer": "Meocap Performer",
    "Now plugin version: ": "当前插件版本: ",
    "Latest plugin version: ": "最新插件版本: ",
    "Source Port": "源端口",
    "FrameId": "帧Id",
    "Performer": "Performer",
    "Target FPS": "目标FPS",
    "End Recording": "结束录制",
    "Start Recording": "开始录制",
    "Load Recording to Animation": "加载录制到动画",
    "NOTE: The model's rest pose must be T-POSE": "注意: 模型的静置姿势必须是 T-POSE",
    "Bind Bones": "绑定骨骼",
    "bones marked with an * are optional.": "标有*的骨骼是可选的.",
    "Auto Detect Bones(VRM Ext.)": "自动检测骨骼(VRM Ext.)",
    "Clear Bones": "清理骨骼",
    "Import Retarget Config": "导入录制配置",
    "Export Retarget Config": "导出录制配置",
    "Config Preset:": "配置预设:",
    "Meocap Tech": "Meocap Tech",

    "Pelvis(Hips)": "骨盆(臀部)",
    "L_UpperLeg": "左_大腿",
    "R_UpperLeg": "右_大腿",
    "Spine": "脊柱",
    "L_LowerLeg": "左_小腿",
    "R_LowerLeg": "右_小腿",
    "Chest": "胸部",
    "L_Foot": "左_脚",
    "R_Foot": "右_脚",
    "UpperChest": "上胸围",
    "L_Toes": "左_脚趾",
    "R_Toes": "右_脚趾",
    "Neck": "脖子",
    "L_Shoulder": "左_肩部",
    "R_Shoulder": "右_肩部",
    "Head": "头",
    "L_UpperArm": "左_上臂",
    "R_UpperArm": "右_上臂",
    "L_LowerArm": "左_小臂",
    "R_LowerArm": "右_小臂",
    "L_Hand": "左_手",
    "R_Hand": "右_手",
    "L_Palm": "左_手掌",
    "R_Palm": "右_手掌",
    "Foot": "脚",
    "UpperLeg": "大腿",
    "LowerLeg": "小腿",
    "Toes": "脚趾",
    "Shoulder": "肩部",
    "UpperArm": "上臂",
    "LowerArm": "小臂",
    "Hand": "手",
}
