name: 'publish_public_docs'
on:
  workflow_dispatch:
  push:
    branches: [ "main" ,"dev"]
jobs:
  upload-to-cloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ossutil2
        run: |
          wget https://gosspublic.alicdn.com/ossutil/1.7.6/ossutil64 -O ossutil
          chmod +x ossutil
          sudo mv ossutil /usr/local/bin

      - name: Upload files to Alibaba Cloud OSS
        env:
          ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          ALIYUN_BUCKET: ${{ secrets.ALIYUN_BUCKET }}
          ALIYUN_OSS_ENDPOINT: ${{ secrets.ALIYUN_OSS_ENDPOINT }}
        run: |
          # Configure ossutil2
          ossutil config -i $ALIYUN_ACCESS_KEY_ID -k $ALIYUN_ACCESS_KEY_SECRET -e $ALIYUN_OSS_ENDPOINT

          # Upload files to OSS
          ossutil cp -r ./public/docs/ oss://$ALIYUN_BUCKET/docs/ --endpoint $ALIYUN_OSS_ENDPOINT
